site_name: Invent x Mines Data challenge 2024
theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Page example: example.md
